let s:vimdir = $MYVIMRC->split("/", v:true)[:-2]->join("/")
command -nargs=1 Source execute printf('source %s/%s', s:vimdir, <q-args>)

Source plugins.vim
Source options.vim
Source keybindings.vim
Source run_buffer.vim
Source search.vim
Source help.vim
Source autocmd.vim
Source term.vim
